-- Player Values
PLAYER_WIDTH = 32
PLAYER_HEIGHT = 32

-- Building Values
BUILDING_MIN_WIDTH = PLAYER_WIDTH
BUILDING_MIN_HEIGHT = 0

-- Projectiles
PROJECTILE_WIDTH = 8
PROJECTILE_HEIGHT = 8

-- Physics
GRAVITY = 200
